### ISSUE TITLE
PDAs need to be runnable even if they won't accept

### ISSUE THREAD

**Issue by bca-benise** [davidbuzatto/YAAS#3]
"The PDA simulation only works with accepted strings!"

This is a gating issue to using YAAS in a classroom setting.  If students make an incorrect PDA, they need to be able to watch it at work to learn why they are wrong.

**Comment by davidbuzatto** [comment]
This will be probably addressed in a future release. PDAs can be tested with unaccepted strings, but not execute the simulation.
