### ISSUE TITLE
Changing empty string symbol

### ISSUE THREAD

**Issue by LockedThread** [davidbuzatto/YAAS#6]
Could you add a configurable way to change empty-string symbol? Lambda is another empty string symbol that is commonly used.

**Comment by davidbuzatto** [comment]
Hello! I saw that you forked the project. Were you able to change the symbol to lambda? If you weren't able to, let me know and I'll help you. I use this tool in a course that I teach annually, so the nomenclature and symbology used adhere to the material I use to teach.

**Comment by LockedThread** [comment]
> Hello! I saw that you forked the project. Were you able to change the symbol to lambda? If you weren't able to, let me know and I'll help you. I use this tool in a course that I teach annually, so the nomenclature and symbology used adhere to the material I use to teach.

I forked it and was able to change it for my use case. Thank you for developing this tool, it has helped a lot of students at my university.

**Comment by davidbuzatto** [comment]
My pleasure! Nice to know that the tool helped you and your colleagues!
