### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by alvino11** [davidbuzatto/YAAS#7]
No help guide and users are left to figure out things on their own... Have not been able to figure out how to make transition lines curved as of now

**Comment by davidbuzatto** [comment]
Hello. I haven't actually prepared a tutorial to teach you how to use the tool. I have a presentation video, but it was recorded in Brazilian Portuguese. If you want, list your questions and I'll answer them. Regarding your question, see the image below.

![image](https://github.com/user-attachments/assets/eb81ceb9-a93c-487d-8539-e0143bb799f9)

**Comment by davidbuzatto** [comment]
Here is the video if you want to take a look: https://www.youtube.com/watch?v=ILxWF1mf8PY

**Comment by alvino11** [comment]
Thanks for the reply..I was able to figure it out.. This program really
helped me in my studies of turing machine, DFA and NFA

**Comment by davidbuzatto** [comment]
My pleasure!
